name: TaskMaster
version: '1.0-SNAPSHOT'
main: me.jacky.taskMaster.TaskMaster
api-version: '1.20'
authors: [ Jacky ]
commands:
  ping:
    description: get sender's ping or ping of target player
    usage: /<command> Optional<Player>
    aliases:
      - delay
  taskmaster:
    description: start game!
    usage: /<command>
  jointeam:
    description: join teams!
    usage: /<command>
  canceltaskmaster:
    description: Cancel and settle TaskMaster game immediately
    usage: /canceltaskmaster
